site_name: doc.jp
site_author: tdwaf
nav:
  - Home: 'index.md'
  - 'Anki Stats': 'stats/stats.md'
  - 'Grammar':
    - 'Home': 'grammar/home.md'
  - 'Goals':
    - 'goals/long-term.md'
    - 'goals/2023/december.md'
  - 'Tool Setup': 
    - 'Yomichan': 'tool-setup/yomichan.md'
    - 'Sentence Mining': 'tool-setup/mining.md'
  - 'Resources':
    - 'Currently Using': 'resources/currently-using.md'
    - 'Not Using Currently': 'resources/not-using.md'
  - 'Study Plan': 'plan/study-plan.md'
theme:
  name: material
  logo: assets/logo/logo.svg
  icon:
    admonition:
      failure: material/exclamation
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.suggest
    - search.highlighting
    - search.share
  palette:
    # Light Mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: indigo
      accent: indigo

    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: slate
      accent: indigo
  custom_dir: overrides
markdown_extensions:
  - toc:
      permalink: true
  - meta
  - admonition
  - attr_list
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
plugins:
  - search
  - macros
extra_css: [ css/styles.css ]
watch:
  - docs/
  - mkdocs.yml