site_name: doc.jp
site_author: tyler
nav:
  - Home: 'index.md'
  - 'Grammar':
    - 'Particles':
      - 'grammar/JFZ/と.md'
      - 'grammar/JFZ/の.md'
    - 'Grammar Points':
      - 'N5 Level Grammar':
        - 'grammar/JFZ/ましょう.md'
        - 'grammar/JFZ/よく.md'
        - 'grammar/JFZ/あんまり.md'
        - 'grammar/JFZ/もう.md'
        - 'grammar/JFZ/を.md'
        - 'grammar/JFZ/まだ.md'
        - 'grammar/JFZ/そして.md'
        - 'grammar/JFZ/あいだ.md'
        - 'grammar/JFZ/い-adjectives.md'
        - 'grammar/JFZ/な-adjectives.md'
  - 'Goals':
    - 'goals/long-term.md'
    - 'goals/2023/october.md'
  - 'Tool Setup': 
    - 'Yomichan': 'tool-setup/yomichan.md'
    - 'Sentence Mining': 'tool-setup/mining.md'
  - 'Resources': 'resources/resources.md'
theme:
  name: material
  icon:
    admonition:
      failure: material/exclamation
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - search.suggest
    - search.highlighting
    - search.share
  palette:
    # Light Mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: indigo
      accent: indigo

    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: slate
      accent: indigo
  custom_dir: overrides
  logo: false
extra_css:
  - css/styles.css
markdown_extensions:
  - toc:
      permalink: true
  - meta
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
