site_name: doc.jp
site_author: tyler
nav:
  - Home: 'index.md'
  - 'Grammar':
    - 'Particles':
      - 'grammar/particles/を.md'
      - 'grammar/particles/と.md'
      - 'grammar/particles/の.md'
      - 'grammar/particles/よ.md'
      - 'grammar/particles/で.md'
      - 'grammar/particles/か.md'
      - 'grammar/particles/に-frequency.md'
    - 'Grammar Points':
      - 'N5 Level Grammar':
        - 'grammar/JFZ/N5/い-adjectives.md'
        - 'grammar/JFZ/N5/な-adjectives.md'
        - 'grammar/JFZ/N5/verb-negatives.md'
        - 'grammar/JFZ/N5/ましょう.md'
        - 'grammar/JFZ/N5/よく.md'
        - 'grammar/JFZ/N5/あんまり.md'
        - 'grammar/JFZ/N5/もう.md'
        - 'grammar/JFZ/N5/まだ.md'
        - 'grammar/JFZ/N5/そして.md'
        - 'grammar/JFZ/N5/あいだ.md'
        - 'grammar/JFZ/N5/から.md'
        - 'grammar/JFZ/N5/でしょう.md'
        - 'grammar/JFZ/N5/ごろ.md'
        - 'grammar/JFZ/N5/ぐらい.md'
        - 'grammar/JFZ/N5/た-form.md'
        - 'grammar/JFZ/N5/て-form.md'
        - 'grammar/JFZ/N5/ください.md'
        - 'grammar/JFZ/N5/ている.md'
        - 'grammar/JFZ/N5/より.md'
      - 'N4 Level Grammar':
        - 'grammar/JFZ/N4/それに.md'
        - 'grammar/JFZ/N4/とおもう.md'
        - 'grammar/JFZ/N4/ぜんぜん.md'
        - 'grammar/JFZ/N4/だいたい.md'
        - 'grammar/JFZ/N4/より.md'
    - 'Misc':
      - 'Misc Grammar Points':
        - 'grammar/misc/なにも.md'
        - 'grammar/misc/どう.md'
        - 'grammar/misc/たち.md'
  - 'Goals':
    - 'goals/long-term.md'
    - 'goals/2023/october.md'
  - 'Tool Setup': 
    - 'Yomichan': 'tool-setup/yomichan.md'
    - 'Sentence Mining': 'tool-setup/mining.md'
  - 'Resources':
    - 'Currently Using': 'resources/currently-using.md'
    - 'Not Using Currently': 'resources/not-using.md'
  - 'Study Plan': 'plan/study-plan.md'
theme:
  name: material
  logo: assets/logo/logo.svg
  icon:
    admonition:
      failure: material/exclamation
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.suggest
    - search.highlighting
    - search.share
  palette:
    # Light Mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: indigo
      accent: indigo

    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: slate
      accent: indigo
  custom_dir: overrides
markdown_extensions:
  - toc:
      permalink: true
  - meta
  - admonition
  - attr_list
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
extra_css: [ css/styles.css ]