site_name: doc.jp
site_author: tyler
nav:
  - Home: 'index.md'
  - 'Grammar':
    - 'grammar/JFZ/ましょう.md'
    - 'grammar/JFZ/よく.md'
    - 'grammar/JFZ/あんまり.md'
    - 'grammar/JFZ/もう.md'
    - 'grammar/JFZ/を.md'
    - 'grammar/JFZ/まだ.md'
    - 'grammar/JFZ/そして.md'
  - 'Goals':
    - 'goals/long-term.md'
    - 'goals/2023/october.md'
  - 'Resources':
    - 'resources/resources.md'
theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - search.suggest
    - search.highlighting
    - search.share
  palette:
    # Light Mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: indigo
      accent: indigo

    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: slate
      accent: indigo
  custom_dir: overrides
  logo: false
extra_css:
  - css/styles.css
markdown_extensions:
  - toc:
      permalink: true
  - meta
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
