site_name: doc.jp
site_author: tdwaf
nav:
  - 'Home':
    - 'index.md'
    - 'Journey': 'home/journey.md'
  - 'Goals':
    - 'goals/index.md'
    - 'goals/short-term.md'
    - 'goals/long-term.md'
  - 'Resources': 'resources/index.md'
  - 'Study Plan': 'plan/study-plan.md'
theme:
  name: material
  logo: assets/logo/logo.svg
  icon:
    admonition:
      failure: material/exclamation
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.suggest
    - search.highlighting
    - search.share
  palette:
    # Light Mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: slate
      accent: indigo
  custom_dir: overrides
markdown_extensions:
  - toc:
      permalink: true
  - meta
  - admonition
  - attr_list
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
plugins: [ search ]
extra_css: [ css/styles.css ]
