site_name: doc.jp
site_author: tyler
nav:
  - Home: 'index.md'
  - 'Grammar':
    - 'grammar/JFZ/ましょう.md'
    - 'grammar/JFZ/よく.md'
    - 'grammar/JFZ/あんまり.md'
    - 'grammar/JFZ/もう.md'
    - 'grammar/JFZ/を.md'
    - 'grammar/JFZ/まだ.md'
    - 'grammar/JFZ/そして.md'
  - 'Goals':
    - 'goals/long-term.md'
    - 'goals/2023/october.md'
  - 'Resources':
    - 'resources/resources.md'
theme:
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - search.suggest
    - search.highlighting
    - search.share
  name: material
extra_css:
  - css/styles.css
markdown_extensions:
  - toc:
      permalink: true
  - meta
  - admonition
  - attr_list
