name: Add Goals For This Month Issue
on:
  schedule:
    - cron: 0 0 1 * *
  workflow_dispatch:

jobs:
  create_issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Get current date
        id: date
        uses: Kaven-Universe/github-action-current-date-time@v1
        with:
          format: "YYYY_MMMM_DD HH_mm_ss_SSS"

      - name: Create Goals Addition Issue
        uses: imjohnbo/issue-bot@v3
        with:
          assignees: "tdwaf"
          labels: "todo, documentation"
          title: "Add goals for ${{ steps.date.outputs.month }}/${{ steps.date.outputs.year }}"
          body: |
            ### What needs to be done

            - [ ] Move current month's goal page to legacy
            - [ ] Add goals page for the current month
          pinned: false
          close-previous: false
