name: ci
on:
  push:
    branches: [main]
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Install mkdocs-material
        run: pip install mkdocs-material
      - name: Install mkdocs-macros-plugin
        run: pip install mkdocs-macros-plugin
      - name: Build docs
        run: mkdocs build
      - name: Publish docs
        run: mkdocs gh-deploy --force