name: ci
on:
  push:
    branches: [main]
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install --upgrade pip && pip install mkdocs mkdocs-gen-files
      - run: pip install mkdocs-material
      - name: Publish docs
        run: mkdocs gh-deploy --force
