name: Update Goals For This Month Issue
on:
  schedule:
    - cron: 0 0 1 * *
  workflow_dispatch:

jobs:
  create_issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Get current date
        id: date
        uses: Kaven-Universe/github-action-current-date-time@v1
        with:
          format: "YYYY_MMMM_DD HH_mm_ss_SSS"

      - name: Update Goals Issue
        uses: imjohnbo/issue-bot@v3
        with:
          assignees: "tdwaf"
          labels: "todo, documentation"
          title: "Update goals for ${{ steps.date.outputs.month }}/${{ steps.date.outputs.year }}"
          body: |
            Monthly goals update! If there are no changes, close this issue with a comment explaining so.

            ### What needs to be done

            - [ ] Refine/update goals
            - [ ] Link issue to pull request updating goals
          pinned: false
          close-previous: false
